### ISSUE TITLE
Add snackbar component on progress/completed user picture upload

### ISSUE THREAD

**Issue by roymoran** [projectunic0rn/mentorship-ui#117]
https://material-ui.com/demos/snackbars/

**Comment by rmjordas** [comment]
Snackbar documentation for `material-ui@1.3.x`:

https://v1-3-0.material-ui.com/demos/snackbars/

**Comment by roymoran** [comment]
awesome thanks @rmjordas for adding the address to the right doc version. I think material is on v3. I'm think we should update to the latest. 

I know you've been making package update on the `bfr` branch do you think we'll be able to update the material-ui package without major issues?

**Comment by rmjordas** [comment]
I updated all of packages to the latest versions except for `@types/styled-components`. I fixed some issues on outdated types on some components and saw a button misaligned. So far, nothing major. 

I guess, the biggest change is moving from ` react-scripts-ts` to `react-scripts@2.1.1`. (I added some links on my PR).

When the active PRs get merged, I'll try to fix any issues that come up.
