### ISSUE TITLE
material-ui-chip-input typescript errors

### ISSUE THREAD

**Issue by rickywid** [projectunic0rn/mentorship-ui#136]
https://www.npmjs.com/package/material-ui-chip-input

im having issues trying to get material-ui-chip-input package to work. typescript is giving me an error.

https://i.imgur.com/ada0mtI.png
https://i.imgur.com/jZpOv9X.png

i was able to get rid of the error by editing the tslint.config file by changing     "noImplicitAny" to false.
https://stackoverflow.com/questions/50555859/typescript-could-not-find-a-declaration-file-for-module-react-cards

then i was getting another error:

Module not found: Can't resolve 'material-ui/AutoComplete/AutoComplete' in '/home/ricky/odinproject/mentorship-ui/node_modules/material-ui-chip-input/lib'

any ideas on how to fix this?

**Comment by rmjordas** [comment]
Yeah, it means that the package does not specify the location for its type definitions. With popular packages, you can do an npm install for `@types/*`, e.g. `@types/react`, but I found nothing for this package so we can add the typings ourselves.

Create a directory in the root where we can add all of our typings. Add the `declare module 'material-ui-chip-input';` (the snippet specified in the error) to a `*.d.ts` file. Then update the TypeScript config file to add the directory or file you just created. Here's the documentation:

[TypeScript Docs: `@types`, `typeRoots` and `types`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)

**Comment by rickywid** [comment]
ill give it a try. thanks
