### ISSUE TITLE
Investigate possibility of using SAS key to upload user image to azure storage

### ISSUE THREAD

**Issue by roymoran** [projectunic0rn/mentorship-ui#148]
In order to avoid exposing the storage access key on the client side lets investigate if we can use a Shared Access Signature to give our client side permission to write blobs to the storage account.

**Comment by rickywid** [comment]
what?...

**Comment by rmjordas** [comment]
If I understand correctly, SAS token generation is performed when a user authenticates with a backend service. This is from Azure docs:

![](https://docs.microsoft.com/en-us/azure/storage/common/media/storage-dotnet-shared-access-signature-part-1/sas-storage-provider-service.png)

**Comment by roymoran** [comment]
@rmjordas the sas key we can generate ourselves manually. We don't have to worry about generating it when authenticating.

**Comment by roymoran** [comment]
If you go to the azure storage account resource you will see where you can generate the sas key. Once generated, I'm wondering if we can use it to authenticate against the storage api to upload the user profile images.

**Comment by roymoran** [comment]
![Screen Shot 2018-12-18 at 11.48.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591a9848a77d7e0020d34010/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455fb6b7191a379ee0c2f59415b49bc21254d58eeb9cb74fce36f34985619e883680d26906e16f8ba801dbb06ba208a1dd3e2bd894ec1fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe44f54a2123362e271336e0a.png)

**Comment by rmjordas** [comment]
Thanks for the info. 👍 

I'll start working on the SAS provided by the Azure console. I'm thinking we should tick only the "Write" checkbox (for file uploads)?
