### ISSUE TITLE
On dashboard, hovering in white space allows click of a mentor, update to have to be on a mentor to view profile

### ISSUE THREAD

**Issue by 2940cristian** [projectunic0rn/mentorship-ui#164]

**Comment by rickywid** [comment]
not sure what you mean. could you clarify?

**Comment by 2940cristian** [comment]
Notice how clicking on our featured users photos take us to their profile. Well clicking on the white space around it redirects us to their profile too. Not so much a bug, more so a little bit of a nuisance since it can be clicked on accident.
