### ISSUE TITLE
On mobile, dashboard featured page mentors titles are blue (should be grey)

### ISSUE THREAD

**Issue by 2940cristian** [projectunic0rn/mentorship-ui#165]

**Comment by rickywid** [comment]
are you talking about the mentor's name or the page name?

this is how the page looks on my computer

https://i.imgur.com/qwHZaYq.png

**Comment by 2940cristian** [comment]
On computer's the links appear fine. However on my google pixel using samsung internet. When we are on a user's dashboard and have mentors with their name and title, their title should appear greyish. On mobile the colors look different.
Desktop: 
![screenshot 47](https://user-images.githubusercontent.com/36054337/49673969-32558700-fa25-11e8-9e34-1707fa2b1ab6.png)

Mobile: 
![screenshot_20181207-133336](https://user-images.githubusercontent.com/36054337/49673986-3b465880-fa25-11e8-8976-36d489459f18.png)

Mobile OnClick:
![screenshot_20181207-133417](https://user-images.githubusercontent.com/36054337/49673994-426d6680-fa25-11e8-8aaa-b0af2ff9c9ad.png)

**Comment by 2940cristian** [comment]
Closing as UI no longer has user's titles on featured page, only stars
