### ISSUE TITLE
Mentor settings bottom navigation positioned above key skills if there are key skills present

### ISSUE THREAD

**Issue by roymoran** [projectunic0rn/mentorship-ui#238]
When a mentor has key skills present on their profile, the bottom navigation on the mentor settings page is positioned above the key skills for some reason.

**Comment by roymoran** [comment]
![Screen Shot 2018-12-18 at 11.40.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591a9848a77d7e0020d34010/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455fb6b7191a379ee0c2f51415b4cbc21254d58eeb9cb74fce36f34985619e883680d26906e16f8ba801dbb06ba208a1dd3e2bd894ec1fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe44c50ac173263e4763e6e0a.png)

**Comment by 2940cristian** [comment]
This is due to the way our bottomNav is currently styled. I'm pushing a PR that fixes the main.tsx height set at 100vh and makes bottomNav positioned to bottom.

**Comment by rickywid** [comment]
@2940cristian is this fixed? i just checked myself and everything looks fine to me.

**Comment by 2940cristian** [comment]
@rickywid It was more so affecting mobile for me. I made a PR to fix it but hasn't been merged yet. My issue on desktop without the changes I made is the save button isn't clickable. If merged we'll see if it fixes our issues.

**Comment by rickywid** [comment]
@2940cristian cool. thanks

**Comment by roymoran** [comment]
@2940cristian great man. I'll take a look.
