### ISSUE TITLE
Production site has console errors for missing web app manifest

### ISSUE THREAD

**Issue by rmjordas** [projectunic0rn/mentorship-ui#291]
I'm getting some console errors on Chrome Version 71.0.3578.98

![manifest404error](https://user-images.githubusercontent.com/27814962/50716767-20b3dd80-10be-11e9-8689-b4ea7dd04233.JPG)

Steps to reproduce:

- Go to https://mentrship.com
- Open Developer Tools console

The web app manifest is declared in this [line on `public/index.html`](https://github.com/projectunic0rn/mentorship-ui/blob/dc432d43c4e4493977291a0816c878358b031651/public/index.html#L22). Running `npm run build`, correctly copies this file (along with the favicons) to a `build` directory. 

Accessing https://www.mentrship.com/manifest.json, results to a text:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by roymoran** [comment]
@rmjordas  RIght now I'm only seeing an error with fetching the scss file

**Comment by roymoran** [comment]
![Screen Shot 2019-01-05 at 12.58.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591a9848a77d7e0020d34010/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226454f66b7191a379ed0c2e59415b4abc21254d58eeb9cb74fce36f34985619e883680d26906e16f8ba801dbb06ba208a1dd3e2bd894ec1fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe74a54a1123466e570366e0a.png)

**Comment by rmjordas** [comment]
Can you please attach a screenshot of the "Application" tab in the developer tools. 

Here's mine:

![mentrshipappdevtools](https://user-images.githubusercontent.com/27814962/50728388-e270f980-1163-11e9-834b-f5a8c68934a0.JPG)

**Comment by roymoran** [comment]
@rmjordas I'll take a look

**Comment by rmjordas** [comment]
Fixed in #299
